In [1]:
from pathlib import Path
import pandas as pd
import json

folder = Path("../book_data/resumable")

summary = []

In [2]:
for year in range(2006, 2026):
    csv_path = folder / f"checkouts_{year}.csv"
    progress_path = folder / f"progress_{year}.json"

    if csv_path.exists() and progress_path.exists():
        progress = json.loads(progress_path.read_text())

        rows = sum(
            len(chunk)
            for chunk in pd.read_csv(csv_path, chunksize=10000)
        )

        summary.append({
            "Year": year,
            "Rows": rows,
            "Download Complete": (
                progress["completed"] == len(progress["blocks"])
            )
        })

summary_df = pd.DataFrame(summary)
display(summary_df)

print("Total rows:", summary_df["Rows"].sum())

ParserError: Error tokenizing data. C error: Expected 11 fields in line 35002, saw 12

In [2]:

from pathlib import Path
import csv

folder = Path("book_data/resumable")

# Inspect the first file
file = folder / "checkouts_2006.csv"

with open(file, newline="", encoding="utf-8") as f:
    reader = csv.reader(f)

    header = next(reader)
    print("Header:", header)
    print("Expected columns:", len(header))

    for row_num, row in enumerate(reader, start=2):
        if len(row) != len(header):
            print("\nFirst mismatched record:")
            print("CSV record:", row_num)
            print("Columns found:", len(row))
            print("Values:", row[:15])
            break

Header: ['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'creator', 'subjects', 'publisher', 'publicationyear']
Expected columns: 11

In [3]:

import csv
from pathlib import Path

folder = Path("book_data/resumable")

results = []

for file in sorted(folder.glob("checkouts_*.csv")):
    with open(file, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)

        total = 0
        mismatched = 0

        for row in reader:
            total += 1
            if len(row) != len(header):
                mismatched += 1

    results.append({
        "Year": file.stem.replace("checkouts_", ""),
        "Rows": total,
        "Header Columns": len(header),
        "Mismatched Rows": mismatched
    })

import pandas as pd
display(pd.DataFrame(results))

    Year    Rows  Header Columns  Mismatched Rows
0   2006  100000              11                0
1   2007  100000              11                0
2   2008  100000              11                0
3   2009  100000              11                0
4   2010  100000              11                0
5   2011  100000              11                0
6   2012  100000              11                0
7   2013  100000              11                0
8   2014  100000              11                0
9   2015  100000              11                0
10  2016  100000              11                0
11  2017  100000              11                0
12  2018  100000              11                0
13  2019  100000              11                0
14  2020  100000              11                0
15  2021  100000              11                0
16  2022  100000              11            65000
17  2023  100000              12                0
18  2024  100000              12                0
19  2025  100000              12                0

In [5]:

import csv
from pathlib import Path

folder = Path("book_data/resumable")

for year in [2006, 2021, 2022, 2023, 2025]:
    file = folder / f"checkouts_{year}.csv"

    with open(file, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)

    print(f"\n{year} ({len(header)} columns)")
    print(header)

2006 (11 columns)
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'creator', 'subjects', 'publisher', 'publicationyear']

2021 (11 columns)
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'creator', 'subjects', 'publisher', 'publicationyear']

2022 (11 columns)
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'creator', 'subjects', 'publisher', 'publicationyear']

2023 (12 columns)
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'isbn', 'creator', 'subjects', 'publisher', 'publicationyear']

2025 (12 columns)
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'isbn', 'creator', 'subjects', 'publisher', 'publicationyear']

In [6]:

import csv
from pathlib import Path

folder = Path("book_data/resumable")

for year in [2006, 2021, 2022, 2023, 2025]:
    file = folder / f"checkouts_{year}.csv"

    print(f"\nYEAR {year}")

    with open(file, newline="", encoding="utf-8") as f:
        reader = csv.reader(f)
        header = next(reader)

        for i, row in enumerate(reader):
            if i % 5000 == 0:
                print(
                    f"Block {i//5000 + 1}: "
                    f"{len(row)} columns, "
                    f"year={row[3] if len(row)>3 else None}, "
                    f"month={row[4] if len(row)>4 else None}, "
                    f"checkouts={row[5] if len(row)>5 else None}"
                )

YEAR 2006
Block 1: 11 columns, year=2006, month=1, checkouts=1
Block 2: 11 columns, year=2006, month=1, checkouts=1
Block 3: 11 columns, year=2006, month=2, checkouts=1
Block 4: 11 columns, year=2006, month=2, checkouts=1
Block 5: 11 columns, year=2006, month=3, checkouts=3
Block 6: 11 columns, year=2006, month=4, checkouts=2
Block 7: 11 columns, year=2006, month=4, checkouts=2
Block 8: 11 columns, year=2006, month=5, checkouts=1
Block 9: 11 columns, year=2006, month=6, checkouts=3
Block 10: 11 columns, year=2006, month=6, checkouts=39
Block 11: 11 columns, year=2006, month=7, checkouts=1
Block 12: 11 columns, year=2006, month=8, checkouts=1
Block 13: 11 columns, year=2006, month=8, checkouts=5
Block 14: 11 columns, year=2006, month=8, checkouts=3
Block 15: 11 columns, year=2006, month=9, checkouts=2
Block 16: 11 columns, year=2006, month=10, checkouts=1
Block 17: 11 columns, year=2006, month=10, checkouts=8
Block 18: 11 columns, year=2006, month=11, checkouts=4
Block 19: 11 columns, year=2006, month=12, checkouts=2
Block 20: 11 columns, year=2006, month=12, checkouts=2

YEAR 2021
Block 1: 11 columns, year=2021, month=1, checkouts=1
Block 2: 11 columns, year=2021, month=1, checkouts=1
Block 3: 11 columns, year=2021, month=2, checkouts=5
Block 4: 11 columns, year=2021, month=3, checkouts=9
Block 5: 11 columns, year=2021, month=3, checkouts=1
Block 6: 11 columns, year=2021, month=4, checkouts=6
Block 7: 11 columns, year=2021, month=4, checkouts=1
Block 8: 11 columns, year=2021, month=5, checkouts=5
Block 9: 11 columns, year=2021, month=6, checkouts=17
Block 10: 11 columns, year=2021, month=6, checkouts=3
Block 11: 11 columns, year=2021, month=7, checkouts=2
Block 12: 11 columns, year=2021, month=8, checkouts=1
Block 13: 11 columns, year=2021, month=9, checkouts=3
Block 14: 11 columns, year=2021, month=9, checkouts=2
Block 15: 11 columns, year=2021, month=9, checkouts=5
Block 16: 11 columns, year=2021, month=10, checkouts=1
Block 17: 11 columns, year=2021, month=11, checkouts=1
Block 18: 11 columns, year=2021, month=11, checkouts=4
Block 19: 11 columns, year=2021, month=12, checkouts=2
Block 20: 11 columns, year=2021, month=12, checkouts=1

YEAR 2022
Block 1: 11 columns, year=2022, month=1, checkouts=2
Block 2: 11 columns, year=2022, month=1, checkouts=3
Block 3: 11 columns, year=2022, month=2, checkouts=1
Block 4: 11 columns, year=2022, month=3, checkouts=1
Block 5: 11 columns, year=2022, month=3, checkouts=1
Block 6: 11 columns, year=2022, month=4, checkouts=1
Block 7: 11 columns, year=2022, month=4, checkouts=1
Block 8: 12 columns, year=2022, month=5, checkouts=6
Block 9: 12 columns, year=2022, month=5, checkouts=6
Block 10: 12 columns, year=2022, month=6, checkouts=1
Block 11: 12 columns, year=2022, month=7, checkouts=5
Block 12: 12 columns, year=2022, month=7, checkouts=1
Block 13: 12 columns, year=2022, month=8, checkouts=3
Block 14: 12 columns, year=2022, month=9, checkouts=1
Block 15: 12 columns, year=2022, month=9, checkouts=1
Block 16: 12 columns, year=2022, month=10, checkouts=1
Block 17: 12 columns, year=2022, month=10, checkouts=1
Block 18: 12 columns, year=2022, month=11, checkouts=3
Block 19: 12 columns, year=2022, month=12, checkouts=2
Block 20: 12 columns, year=2022, month=12, checkouts=1

YEAR 2023
Block 1: 12 columns, year=2023, month=1, checkouts=1
Block 2: 12 columns, year=2023, month=2, checkouts=13
Block 3: 12 columns, year=2023, month=2, checkouts=2
Block 4: 12 columns, year=2023, month=2, checkouts=7
Block 5: 12 columns, year=2023, month=3, checkouts=1
Block 6: 12 columns, year=2023, month=9, checkouts=1
Block 7: 12 columns, year=2023, month=9, checkouts=2
Block 8: 12 columns, year=2023, month=10, checkouts=8
Block 9: 12 columns, year=2023, month=11, checkouts=2
Block 10: 12 columns, year=2023, month=11, checkouts=7
Block 11: 12 columns, year=2023, month=4, checkouts=25
Block 12: 12 columns, year=2023, month=4, checkouts=2
Block 13: 12 columns, year=2023, month=5, checkouts=1
Block 14: 12 columns, year=2023, month=6, checkouts=1
Block 15: 12 columns, year=2023, month=6, checkouts=1
Block 16: 12 columns, year=2023, month=7, checkouts=2
Block 17: 12 columns, year=2023, month=7, checkouts=2
Block 18: 12 columns, year=2023, month=8, checkouts=1
Block 19: 12 columns, year=2023, month=12, checkouts=1
Block 20: 12 columns, year=2023, month=12, checkouts=3

YEAR 2025
Block 1: 12 columns, year=2025, month=1, checkouts=1
Block 2: 12 columns, year=2025, month=2, checkouts=2
Block 3: 12 columns, year=2025, month=2, checkouts=1
Block 4: 12 columns, year=2025, month=3, checkouts=1
Block 5: 12 columns, year=2025, month=3, checkouts=1
Block 6: 12 columns, year=2025, month=4, checkouts=1
Block 7: 12 columns, year=2025, month=4, checkouts=1
Block 8: 12 columns, year=2025, month=5, checkouts=5
Block 9: 12 columns, year=2025, month=6, checkouts=25
Block 10: 12 columns, year=2025, month=6, checkouts=2
Block 11: 12 columns, year=2025, month=7, checkouts=1
Block 12: 12 columns, year=2025, month=7, checkouts=1
Block 13: 12 columns, year=2025, month=9, checkouts=1
Block 14: 12 columns, year=2025, month=9, checkouts=1
Block 15: 12 columns, year=2025, month=10, checkouts=1
Block 16: 12 columns, year=2025, month=10, checkouts=1
Block 17: 12 columns, year=2025, month=8, checkouts=1
Block 18: 12 columns, year=2025, month=11, checkouts=2
Block 19: 12 columns, year=2025, month=12, checkouts=1
Block 20: 12 columns, year=2025, month=12, checkouts=3

In [7]:
# Repair 2022 code


import csv
from pathlib import Path

source = Path("book_data/resumable/checkouts_2022.csv")
output_dir = Path("book_data/repaired")
output_dir.mkdir(parents=True, exist_ok=True)

destination = output_dir / "checkouts_2022.csv"

columns = [
    "usageclass", "checkouttype", "materialtype",
    "checkoutyear", "checkoutmonth", "checkouts",
    "title", "isbn", "creator", "subjects",
    "publisher", "publicationyear"
]

repaired = 0
preserved = 0

with open(source, newline="", encoding="utf-8") as infile, \
     open(destination, "w", newline="", encoding="utf-8") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile)

    next(reader)
    writer.writerow(columns)

    for row in reader:
        if len(row) == 11:
            # Insert missing ISBN after title
            row.insert(7, "")
            repaired += 1

        elif len(row) == 12:
            preserved += 1

        else:
            raise ValueError(
                f"Unexpected column count: {len(row)}"
            )

        writer.writerow(row)

print(f"Rows with ISBN inserted: {repaired:,}")
print(f"Rows already 12 columns: {preserved:,}")
print(f"Total rows: {repaired + preserved:,}")
print(f"Saved to: {destination}")

Rows with ISBN inserted: 35,000
Rows already 12 columns: 65,000
Total rows: 100,000
Saved to: book_data/repaired/checkouts_2022.csv

In [8]:
# Standardize the years


import csv
from pathlib import Path

source_dir = Path("book_data/resumable")
output_dir = Path("book_data/repaired")
output_dir.mkdir(exist_ok=True)

columns = [
    "usageclass", "checkouttype", "materialtype",
    "checkoutyear", "checkoutmonth", "checkouts",
    "title", "isbn", "creator", "subjects",
    "publisher", "publicationyear"
]

for year in list(range(2006, 2022)) + list(range(2023, 2026)):
    source = source_dir / f"checkouts_{year}.csv"
    destination = output_dir / f"checkouts_{year}.csv"

    with open(source, newline="", encoding="utf-8") as infile, \
         open(destination, "w", newline="", encoding="utf-8") as outfile:

        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        next(reader)
        writer.writerow(columns)

        count = 0

        for row in reader:
            if len(row) == 11:
                row.insert(7, "")
            elif len(row) != 12:
                raise ValueError(
                    f"{year}: Unexpected {len(row)} columns"
                )

            writer.writerow(row)
            count += 1

    print(f"{year}: {count:,} rows repaired")

2006: 100,000 rows repaired
2007: 100,000 rows repaired
2008: 100,000 rows repaired
2009: 100,000 rows repaired
2010: 100,000 rows repaired
2011: 100,000 rows repaired
2012: 100,000 rows repaired
2013: 100,000 rows repaired
2014: 100,000 rows repaired
2015: 100,000 rows repaired
2016: 100,000 rows repaired
2017: 100,000 rows repaired
2018: 100,000 rows repaired
2019: 100,000 rows repaired
2020: 100,000 rows repaired
2021: 100,000 rows repaired
2023: 100,000 rows repaired
2024: 100,000 rows repaired
2025: 100,000 rows repaired

In [9]:

import pandas as pd
from pathlib import Path

folder = Path("book_data/repaired")
files = sorted(folder.glob("checkouts_*.csv"))

df = pd.concat(
    [
        pd.read_csv(
            file,
            dtype={"isbn": "string"},
            low_memory=False
        )
        for file in files
    ],
    ignore_index=True
)

print("Shape:", df.shape)
print("Years:", df["checkoutyear"].min(),
      "to", df["checkoutyear"].max())

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
display(df.isna().sum())

print("\nSample:")
display(df.head())

Shape: (2000000, 12)
Years: 2006 to 2025

Column names:
['usageclass', 'checkouttype', 'materialtype', 'checkoutyear', 'checkoutmonth', 'checkouts', 'title', 'isbn', 'creator', 'subjects', 'publisher', 'publicationyear']

Data types:
usageclass            str
checkouttype          str
materialtype          str
checkoutyear        int64
checkoutmonth       int64
checkouts           int64
title                 str
isbn               string
creator               str
subjects              str
publisher             str
publicationyear       str
dtype: object

Missing values:

usageclass               0
checkouttype             0
materialtype             0
checkoutyear             0
checkoutmonth            0
checkouts                0
title                    1
isbn               1660607
creator             323205
subjects            272346
publisher           394705
publicationyear     416218
dtype: int64

Sample:

,usageclass,checkouttype,materialtype,checkoutyear,checkoutmonth,checkouts,title,isbn,creator,subjects,publisher,publicationyear
0,Physical,Horizon,BOOK,2006,1,1,Costume / written by L. Rowland-Warne.,<NA>,"Rowland-Warne, L.","Costume Juvenile literature, Costume History J...","Dorling Kindersley Pub.,",2000.
1,Physical,Horizon,BOOK,2006,1,1,The forbidden land / Kate Forsyth.,<NA>,"Forsyth, Kate, 1966-","Witches Fiction, Fantasy fiction Australian","Roc,",2001.
2,Physical,Horizon,BOOK,2006,1,1,presumption of death,<NA>,NaN,"War stories, Historical fiction, Mystery ficti...",NaN,NaN
3,Physical,Horizon,BOOK,2006,1,2,Magazine illustration,<NA>,NaN,Illustrated periodicals,NaN,NaN
4,Physical,Horizon,VIDEODISC,2006,1,12,"Greece, Turkey, Israel & Egypt [videorecording...",<NA>,NaN,"Greece Description and travel, Turkey Descript...","Questar, Inc.,",c2001.

In [10]:
# Verify alignment

import pandas as pd
from pathlib import Path

folder = Path("book_data/repaired")

expected_cols = [
    "usageclass", "checkouttype", "materialtype",
    "checkoutyear", "checkoutmonth", "checkouts",
    "title", "isbn", "creator", "subjects",
    "publisher", "publicationyear"
]

results = []

for year in range(2006, 2026):
    path = folder / f"checkouts_{year}.csv"

    df_year = pd.read_csv(
        path,
        dtype="string",
        low_memory=False
    )

    # Validate column names
    columns_ok = df_year.columns.tolist() == expected_cols

    # Convert numeric fields
    years = pd.to_numeric(
        df_year["checkoutyear"], errors="coerce"
    )
    months = pd.to_numeric(
        df_year["checkoutmonth"], errors="coerce"
    )
    checkouts = pd.to_numeric(
        df_year["checkouts"], errors="coerce"
    )

    # Check for invalid values
    bad_years = (~years.eq(year)).sum()
    bad_months = (~months.between(1, 12)).sum()
    bad_checkouts = (
        checkouts.isna() | (checkouts < 0) |
        (checkouts % 1 != 0)
    ).sum()

    # Publication year should generally be a year
    pub = df_year["publicationyear"].dropna()
    suspicious_pub = (
        ~pub.str.fullmatch(r"\d{4}")
    ).sum()

    # ISBN should be empty or look like an identifier
    isbn = df_year["isbn"].dropna()
    suspicious_isbn = (
        ~isbn.str.fullmatch(r"[\dXx\- ]{10,20}")
    ).sum()

    results.append({
        "Year": year,
        "Rows": len(df_year),
        "Columns OK": columns_ok,
        "Bad Years": bad_years,
        "Bad Months": bad_months,
        "Bad Checkouts": bad_checkouts,
        "Suspicious ISBN": suspicious_isbn,
        "Suspicious Publication Year": suspicious_pub
    })

results_df = pd.DataFrame(results)
display(results_df)

print("\nTOTAL ROWS:", results_df["Rows"].sum())

,Year,Rows,Columns OK,Bad Years,Bad Months,Bad Checkouts,Suspicious ISBN,Suspicious Publication Year
0,2006,100000,True,0,0,0,0,32320
1,2007,100000,True,0,0,0,0,35597
2,2008,100000,True,0,0,0,0,42372
3,2009,100000,True,0,0,0,0,45729
4,2010,100000,True,0,0,0,0,53558
5,2011,100000,True,0,0,0,0,57159
6,2012,100000,True,0,0,0,0,61045
7,2013,100000,True,0,0,0,0,65392
8,2014,100000,True,0,0,0,0,67104
9,2015,100000,True,0,0,0,0,66129
10,2016,100000,True,0,0,0,0,68616
11,2017,100000,True,0,0,0,0,62728
12,2018,100000,True,0,0,0,0,63282
13,2019,100000,True,0,0,0,0,66064
14,2020,100000,True,0,0,0,0,37793
15,2021,100000,True,0,0,0,0,55707
16,2022,100000,True,0,0,0,26421,52979
17,2023,100000,True,0,0,0,48896,56063
18,2024,100000,True,0,0,0,41873,50950
19,2025,100000,True,0,0,0,38359,47345

TOTAL ROWS: 2000000

In [11]:

import pandas as pd
from pathlib import Path

folder = Path("book_data/repaired")

for year in [2015, 2022, 2023, 2025]:
    df = pd.read_csv(
        folder / f"checkouts_{year}.csv",
        dtype="string"
    )

    print(f"\n{'=' * 20} YEAR {year} {'=' * 20}")

    # Show suspicious ISBN values
    isbn = df["isbn"].dropna()
    suspicious_isbn = isbn[
        ~isbn.str.fullmatch(r"[\dXx\- ]{10,20}")
    ]

    print("\nSuspicious ISBN examples:")
    print(suspicious_isbn.head(8).tolist())

    # Show suspicious publication years
    pub = df["publicationyear"].dropna()
    suspicious_pub = pub[
        ~pub.str.fullmatch(r"\d{4}")
    ]

    print("\nSuspicious publication year examples:")
    print(suspicious_pub.head(8).tolist())

    # Show full metadata rows where ISBN looks suspicious
    if not suspicious_isbn.empty:
        print("\nFull rows with suspicious ISBN:")
        display(
            df.loc[
                suspicious_isbn.index[:5],
                ["title", "isbn", "creator",
                 "subjects", "publisher", "publicationyear"]
            ]
        )

==================== YEAR 2015 ====================

Suspicious ISBN examples:
[]

Suspicious publication year examples:
['c2006.', '1998.', '1998.', 'c1984.', '2000-', '2014.', 'p2009.', '1903.']

==================== YEAR 2022 ====================

Suspicious ISBN examples:
['1566892538, 9781566892537', '0970601980, 9780970601988', '0765386631, 9780765386632', '0634053426, 9780634053429', '1974701018, 9781974701018', '0062966847, 0062966855, 9780062966841, 9780062966858', '0393248216, 9780393248210', '1481427342, 9781481427340']

Suspicious publication year examples:
['[2020]', '2019.', '[2016]', '[2014]', '[2019]', '[2021]', '[2020]', '[2021]']

Full rows with suspicious ISBN:

,title,isbn,creator,subjects,publisher,publicationyear
35001,Netsuke : a novel / Rikki Ducornet.,"1566892538, 9781566892537","Ducornet, Rikki, 1943-","Psychoanalysts Fiction, Psychoses Fiction, Psy...","Coffee House Press,",2011.
35002,Now you see it : simple visualization techniqu...,"0970601980, 9780970601988","Few, Stephen","Information visualization, Quantitative resear...","Analytics Press,",[2009]
35003,Death's end / Cixin Liu ; translated by Ken Liu.,"0765386631, 9780765386632","Liu, Cixin","Human alien encounters Fiction, Imaginary wars...","TOR, a Tom Doherty Associates Book",[2019]
35009,101 drum tips : stuff all the pros know and us...,"0634053426, 9780634053429","Schroedl, Scott","Drum set Methods Self instruction, Drum set St...","H. Leonard,",[2003]
35012,"Food wars! = Shokugeki no soma. 26, Second bou...","1974701018, 9781974701018","Tsukuda, Yuto, 1989-","Teenage boys Comic books strips etc, Cooking s...","VIZ Media, LLC,",[2018]

==================== YEAR 2023 ====================

Suspicious ISBN examples:
['0316537195, 0316537241, 9780316537186, 9780316537193, 9780316537247, 9780316537254', '1250800811, 9781250800817', '1523089865, 9781523089864, 9781523089871, 9781523089888', '0312652917, 9780312652913', '0744039916, 9780744039917', '0593100816, 9780593100813', '0802779662, 9780802779663', '1555975259, 9781555975258']

Suspicious publication year examples:
['2020.', '2021.', '[2020]', '2010.', '©2021', '[2022]', '[2020]', '[2022]']

Full rows with suspicious ISBN:

,title,isbn,creator,subjects,publisher,publicationyear
0,Horrid / Katrina Leno.,"0316537195, 0316537241, 9780316537186, 9780316...","Leno, Katrina","Eating disorders Juvenile fiction, Sisters Juv...","Little, Brown and Company,",2020.
1,Ace of spades / Faridah Àbíké-Íyímídé,"1250800811, 9781250800817","Àbíké-Íyímídé, Faridah","Private schools Fiction, African American teen...","Feiwel & Friends ,",2021.
2,Touching the jaguar : transforming fear into a...,"1523089865, 9781523089864, 9781523089871, 9781...","Perkins, John, 1945-","Perkins John 1945, United States National Secu...","Berrett-Koehler Publishers,",[2020]
7,Wicked appetite / Janet Evanovich.,"0312652917, 9780312652913","Evanovich, Janet","Witches Fiction, Bakers Fiction, Bakeries Fict...","St. Martin's Press,",2010.
8,"Allies : real talk about showing up, screwing ...","0744039916, 9780744039917",<NA>,"Equality Juvenile literature, Social movements...","DK, a division of Penguin Random House LLC,",©2021

==================== YEAR 2025 ====================

Suspicious ISBN examples:
['1481425544, 9781481425544', '153171692X, 9781531716929', '0465002633, 9780465002634', '0500252548, 9780500252543', '17069107', '0425289362, 0425289370, 9780425289365, 9780425289372', '1534111417, 9781534111417', '1250182085, 9781250182081']

Suspicious publication year examples:
['2015.', '[2024]', '2007.', '2022.', '1992?.', '2003.', '2024.', '[2018]']

Full rows with suspicious ISBN:

,title,isbn,creator,subjects,publisher,publicationyear
0,Peanuts. Snoopy takes off! / by Charles M. Sch...,"1481425544, 9781481425544","Schulz, Charles M. (Charles Monroe), 1922-2000,","Snoopy Fictitious character Juvenile fiction, ...","Simon Spotlight,",2015.
1,Cobra. Rebellion. Season three / a New Picture...,"153171692X, 9781531716929",<NA>,"Prime ministers Great Britain Drama, Crisis ma...","PBS,",[2024]
2,"The art spirit : notes, articles, fragments of...","0465002633, 9780465002634","Henri, Robert, 1865-1929","Art, Art Technique, Art appreciation","Basic Books,",2007.
5,Catholica : the visual culture of Catholicism ...,"0500252548, 9780500252543","Ivanič, Suzanna","Catholic Church In art, Catholic Church Liturg...","Thames & Hudson Ltd,",2022.
13,SET THE TONE (GUNS & ROSES) (CD) [sound record...,17069107,Ghostface Killah.,Rap Hip Hop,"Mass Appeal Records,",2024.

In [12]:
# Suspicious ISBN values likely due to library cataloguing and not due to misalignment of columns